import type { SolarizedTheme } from '../solarized';
import type { ExporterConfig } from './types';

function hexColor(
  theme: SolarizedTheme,
  colorName: keyof SolarizedTheme
): string {
  return theme.get(colorName).to('srgb').toString({ format: 'hex' });
}

function exportAlacrittyDark(theme: SolarizedTheme): string {
  return `# Solarized Dark theme for Alacritty
# Generated by SolarSystem

[colors.primary]
background = '${hexColor(theme, 'base03')}'
foreground = '${hexColor(theme, 'base0')}'

[colors.cursor]
cursor = '${hexColor(theme, 'base1')}'
text = '${hexColor(theme, 'base03')}'

[colors.selection]
background = '${hexColor(theme, 'base02')}'
text = '${hexColor(theme, 'base1')}'

[colors.normal]
black = '${hexColor(theme, 'base02')}'
red = '${hexColor(theme, 'red')}'
green = '${hexColor(theme, 'green')}'
yellow = '${hexColor(theme, 'yellow')}'
blue = '${hexColor(theme, 'blue')}'
magenta = '${hexColor(theme, 'magenta')}'
cyan = '${hexColor(theme, 'cyan')}'
white = '${hexColor(theme, 'base2')}'

[colors.bright]
black = '${hexColor(theme, 'base03')}'
red = '${hexColor(theme, 'orange')}'
green = '${hexColor(theme, 'base01')}'
yellow = '${hexColor(theme, 'base00')}'
blue = '${hexColor(theme, 'base0')}'
magenta = '${hexColor(theme, 'violet')}'
cyan = '${hexColor(theme, 'base1')}'
white = '${hexColor(theme, 'base3')}'
`;
}

function exportAlacrittyLight(theme: SolarizedTheme): string {
  return `# Solarized Light theme for Alacritty
# Generated by SolarSystem

[colors.primary]
background = '${hexColor(theme, 'base3')}'
foreground = '${hexColor(theme, 'base00')}'

[colors.cursor]
cursor = '${hexColor(theme, 'base01')}'
text = '${hexColor(theme, 'base3')}'

[colors.selection]
background = '${hexColor(theme, 'base2')}'
text = '${hexColor(theme, 'base01')}'

[colors.normal]
black = '${hexColor(theme, 'base2')}'
red = '${hexColor(theme, 'red')}'
green = '${hexColor(theme, 'green')}'
yellow = '${hexColor(theme, 'yellow')}'
blue = '${hexColor(theme, 'blue')}'
magenta = '${hexColor(theme, 'magenta')}'
cyan = '${hexColor(theme, 'cyan')}'
white = '${hexColor(theme, 'base02')}'

[colors.bright]
black = '${hexColor(theme, 'base3')}'
red = '${hexColor(theme, 'orange')}'
green = '${hexColor(theme, 'base1')}'
yellow = '${hexColor(theme, 'base00')}'
blue = '${hexColor(theme, 'base0')}'
magenta = '${hexColor(theme, 'violet')}'
cyan = '${hexColor(theme, 'base01')}'
white = '${hexColor(theme, 'base03')}'
`;
}

export const alacrittyDarkExporter: ExporterConfig = {
  id: 'alacritty-dark',
  name: 'Alacritty (Dark)',
  description: 'Alacritty terminal config for dark mode',
  fileExtension: 'toml',
  fileName: 'solarized-dark.toml',
  colorScheme: 'dark',
  export: exportAlacrittyDark,
};

export const alacrittyLightExporter: ExporterConfig = {
  id: 'alacritty-light',
  name: 'Alacritty (Light)',
  description: 'Alacritty terminal config for light mode',
  fileExtension: 'toml',
  fileName: 'solarized-light.toml',
  colorScheme: 'light',
  export: exportAlacrittyLight,
};
