import type { SolarizedTheme } from '../solarized';
import type { ExporterConfig } from './types';

function hexColor(
  theme: SolarizedTheme,
  colorName: keyof SolarizedTheme
): string {
  return theme.get(colorName).to('srgb').toString({ format: 'hex' });
}

function exportGhosTTYDark(theme: SolarizedTheme): string {
  return `# Solarized Dark theme for Ghostty
# Generated by SolarSystem

# Background and foreground
background = ${hexColor(theme, 'base03')}
foreground = ${hexColor(theme, 'base0')}

# Cursor
cursor-color = ${hexColor(theme, 'base1')}
cursor-text = ${hexColor(theme, 'base03')}

# Selection
selection-background = ${hexColor(theme, 'base02')}
selection-foreground = ${hexColor(theme, 'base1')}

# Black
palette = 0=${hexColor(theme, 'base02')}
palette = 8=${hexColor(theme, 'base03')}

# Red
palette = 1=${hexColor(theme, 'red')}
palette = 9=${hexColor(theme, 'orange')}

# Green
palette = 2=${hexColor(theme, 'green')}
palette = 10=${hexColor(theme, 'base01')}

# Yellow
palette = 3=${hexColor(theme, 'yellow')}
palette = 11=${hexColor(theme, 'base00')}

# Blue
palette = 4=${hexColor(theme, 'blue')}
palette = 12=${hexColor(theme, 'base0')}

# Magenta
palette = 5=${hexColor(theme, 'magenta')}
palette = 13=${hexColor(theme, 'violet')}

# Cyan
palette = 6=${hexColor(theme, 'cyan')}
palette = 14=${hexColor(theme, 'base1')}

# White
palette = 7=${hexColor(theme, 'base2')}
palette = 15=${hexColor(theme, 'base3')}
`;
}

function exportGhosTTYLight(theme: SolarizedTheme): string {
  return `# Solarized Light theme for Ghostty
# Generated by SolarSystem

# Background and foreground
background = ${hexColor(theme, 'base3')}
foreground = ${hexColor(theme, 'base00')}

# Cursor
cursor-color = ${hexColor(theme, 'base01')}
cursor-text = ${hexColor(theme, 'base3')}

# Selection
selection-background = ${hexColor(theme, 'base2')}
selection-foreground = ${hexColor(theme, 'base01')}

# Black
palette = 0=${hexColor(theme, 'base2')}
palette = 8=${hexColor(theme, 'base3')}

# Red
palette = 1=${hexColor(theme, 'red')}
palette = 9=${hexColor(theme, 'orange')}

# Green
palette = 2=${hexColor(theme, 'green')}
palette = 10=${hexColor(theme, 'base1')}

# Yellow
palette = 3=${hexColor(theme, 'yellow')}
palette = 11=${hexColor(theme, 'base00')}

# Blue
palette = 4=${hexColor(theme, 'blue')}
palette = 12=${hexColor(theme, 'base0')}

# Magenta
palette = 5=${hexColor(theme, 'magenta')}
palette = 13=${hexColor(theme, 'violet')}

# Cyan
palette = 6=${hexColor(theme, 'cyan')}
palette = 14=${hexColor(theme, 'base01')}

# White
palette = 7=${hexColor(theme, 'base02')}
palette = 15=${hexColor(theme, 'base03')}
`;
}

export const ghosttyDarkExporter: ExporterConfig = {
  id: 'ghostty-dark',
  name: 'Ghostty (Dark)',
  description: 'Ghostty terminal config for dark mode',
  fileExtension: 'conf',
  fileName: 'solarized-dark',
  colorScheme: 'dark',
  export: exportGhosTTYDark,
};

export const ghosttyLightExporter: ExporterConfig = {
  id: 'ghostty-light',
  name: 'Ghostty (Light)',
  description: 'Ghostty terminal config for light mode',
  fileExtension: 'conf',
  fileName: 'solarized-light',
  colorScheme: 'light',
  export: exportGhosTTYLight,
};
