import type { SolarizedTheme } from '../solarized';
import type { ExporterConfig } from './types';

function hexColor(
  theme: SolarizedTheme,
  colorName: keyof SolarizedTheme
): string {
  return theme.get(colorName).to('srgb').toString({ format: 'hex' });
}

function exportKittyDark(theme: SolarizedTheme): string {
  return `# Solarized Dark theme for Kitty
# Generated by SolarSystem

# Basic colors
foreground ${hexColor(theme, 'base0')}
background ${hexColor(theme, 'base03')}
selection_foreground ${hexColor(theme, 'base1')}
selection_background ${hexColor(theme, 'base02')}

# Cursor colors
cursor ${hexColor(theme, 'base1')}
cursor_text_color ${hexColor(theme, 'base03')}

# URL underline color when hovering with mouse
url_color ${hexColor(theme, 'blue')}

# Black
color0 ${hexColor(theme, 'base02')}
color8 ${hexColor(theme, 'base03')}

# Red
color1 ${hexColor(theme, 'red')}
color9 ${hexColor(theme, 'orange')}

# Green
color2 ${hexColor(theme, 'green')}
color10 ${hexColor(theme, 'base01')}

# Yellow
color3 ${hexColor(theme, 'yellow')}
color11 ${hexColor(theme, 'base00')}

# Blue
color4 ${hexColor(theme, 'blue')}
color12 ${hexColor(theme, 'base0')}

# Magenta
color5 ${hexColor(theme, 'magenta')}
color13 ${hexColor(theme, 'violet')}

# Cyan
color6 ${hexColor(theme, 'cyan')}
color14 ${hexColor(theme, 'base1')}

# White
color7 ${hexColor(theme, 'base2')}
color15 ${hexColor(theme, 'base3')}
`;
}

function exportKittyLight(theme: SolarizedTheme): string {
  return `# Solarized Light theme for Kitty
# Generated by SolarSystem

# Basic colors
foreground ${hexColor(theme, 'base00')}
background ${hexColor(theme, 'base3')}
selection_foreground ${hexColor(theme, 'base01')}
selection_background ${hexColor(theme, 'base2')}

# Cursor colors
cursor ${hexColor(theme, 'base01')}
cursor_text_color ${hexColor(theme, 'base3')}

# URL underline color when hovering with mouse
url_color ${hexColor(theme, 'blue')}

# Black
color0 ${hexColor(theme, 'base2')}
color8 ${hexColor(theme, 'base3')}

# Red
color1 ${hexColor(theme, 'red')}
color9 ${hexColor(theme, 'orange')}

# Green
color2 ${hexColor(theme, 'green')}
color10 ${hexColor(theme, 'base1')}

# Yellow
color3 ${hexColor(theme, 'yellow')}
color11 ${hexColor(theme, 'base00')}

# Blue
color4 ${hexColor(theme, 'blue')}
color12 ${hexColor(theme, 'base0')}

# Magenta
color5 ${hexColor(theme, 'magenta')}
color13 ${hexColor(theme, 'violet')}

# Cyan
color6 ${hexColor(theme, 'cyan')}
color14 ${hexColor(theme, 'base01')}

# White
color7 ${hexColor(theme, 'base02')}
color15 ${hexColor(theme, 'base03')}
`;
}

export const kittyDarkExporter: ExporterConfig = {
  id: 'kitty-dark',
  name: 'Kitty (Dark)',
  description: 'Kitty terminal config for dark mode',
  fileExtension: 'conf',
  fileName: 'solarized-dark.conf',
  colorScheme: 'dark',
  export: exportKittyDark,
};

export const kittyLightExporter: ExporterConfig = {
  id: 'kitty-light',
  name: 'Kitty (Light)',
  description: 'Kitty terminal config for light mode',
  fileExtension: 'conf',
  fileName: 'solarized-light.conf',
  colorScheme: 'light',
  export: exportKittyLight,
};
