import type { SolarizedTheme } from '../solarized';
import type { ExporterConfig } from './types';

function hexColor(
  theme: SolarizedTheme,
  colorName: keyof SolarizedTheme
): string {
  return theme.get(colorName).to('srgb').toString({ format: 'hex' });
}

function exportWeztermDark(theme: SolarizedTheme): string {
  return `-- Solarized Dark theme for WezTerm
-- Generated by SolarSystem
-- Add this to your wezterm.lua config

return {
  foreground = '${hexColor(theme, 'base0')}',
  background = '${hexColor(theme, 'base03')}',

  cursor_bg = '${hexColor(theme, 'base1')}',
  cursor_fg = '${hexColor(theme, 'base03')}',
  cursor_border = '${hexColor(theme, 'base1')}',

  selection_fg = '${hexColor(theme, 'base1')}',
  selection_bg = '${hexColor(theme, 'base02')}',

  scrollbar_thumb = '${hexColor(theme, 'base01')}',
  split = '${hexColor(theme, 'base01')}',

  ansi = {
    '${hexColor(theme, 'base02')}',  -- black
    '${hexColor(theme, 'red')}',     -- red
    '${hexColor(theme, 'green')}',   -- green
    '${hexColor(theme, 'yellow')}',  -- yellow
    '${hexColor(theme, 'blue')}',    -- blue
    '${hexColor(theme, 'magenta')}', -- magenta
    '${hexColor(theme, 'cyan')}',    -- cyan
    '${hexColor(theme, 'base2')}',   -- white
  },

  brights = {
    '${hexColor(theme, 'base03')}',  -- bright black
    '${hexColor(theme, 'orange')}',  -- bright red
    '${hexColor(theme, 'base01')}',  -- bright green
    '${hexColor(theme, 'base00')}',  -- bright yellow
    '${hexColor(theme, 'base0')}',   -- bright blue
    '${hexColor(theme, 'violet')}',  -- bright magenta
    '${hexColor(theme, 'base1')}',   -- bright cyan
    '${hexColor(theme, 'base3')}',   -- bright white
  },
}
`;
}

function exportWeztermLight(theme: SolarizedTheme): string {
  return `-- Solarized Light theme for WezTerm
-- Generated by SolarSystem
-- Add this to your wezterm.lua config

return {
  foreground = '${hexColor(theme, 'base00')}',
  background = '${hexColor(theme, 'base3')}',

  cursor_bg = '${hexColor(theme, 'base01')}',
  cursor_fg = '${hexColor(theme, 'base3')}',
  cursor_border = '${hexColor(theme, 'base01')}',

  selection_fg = '${hexColor(theme, 'base01')}',
  selection_bg = '${hexColor(theme, 'base2')}',

  scrollbar_thumb = '${hexColor(theme, 'base1')}',
  split = '${hexColor(theme, 'base1')}',

  ansi = {
    '${hexColor(theme, 'base2')}',   -- black
    '${hexColor(theme, 'red')}',     -- red
    '${hexColor(theme, 'green')}',   -- green
    '${hexColor(theme, 'yellow')}',  -- yellow
    '${hexColor(theme, 'blue')}',    -- blue
    '${hexColor(theme, 'magenta')}', -- magenta
    '${hexColor(theme, 'cyan')}',    -- cyan
    '${hexColor(theme, 'base02')}',  -- white
  },

  brights = {
    '${hexColor(theme, 'base3')}',   -- bright black
    '${hexColor(theme, 'orange')}',  -- bright red
    '${hexColor(theme, 'base1')}',   -- bright green
    '${hexColor(theme, 'base00')}',  -- bright yellow
    '${hexColor(theme, 'base0')}',   -- bright blue
    '${hexColor(theme, 'violet')}',  -- bright magenta
    '${hexColor(theme, 'base01')}',  -- bright cyan
    '${hexColor(theme, 'base03')}',  -- bright white
  },
}
`;
}

export const weztermDarkExporter: ExporterConfig = {
  id: 'wezterm-dark',
  name: 'WezTerm (Dark)',
  description: 'WezTerm config for dark mode',
  fileExtension: 'lua',
  fileName: 'solarized-dark.lua',
  colorScheme: 'dark',
  export: exportWeztermDark,
};

export const weztermLightExporter: ExporterConfig = {
  id: 'wezterm-light',
  name: 'WezTerm (Light)',
  description: 'WezTerm config for light mode',
  fileExtension: 'lua',
  fileName: 'solarized-light.lua',
  colorScheme: 'light',
  export: exportWeztermLight,
};
